[package]
name = "n16-config"
version.workspace = true
edition.workspace = true

[dependencies]
n16-theme.workspace = true

knuffel.workspace = true

miette = { version="5.10.0", features=["fancy"] }
