[workspace]
members = [
  "n16-application", "n16-daemon",
  "n16-ipc",
  "n16-launcher",
  "n16-theme",
  "n16-widget",
]

[workspace.dependencies]
n16-theme = { path = "./n16-theme" }
n16-widget = { path = "./n16-widget" }
n16-launcher = { path = "./n16-launcher" }
n16-application = { path = "./n16-application" }
n16-ipc = { path = "./n16-ipc" }
n16-daemon = { path = "./n16-daemon" }

iced = { version = "0.13.1", features = ["advanced", "image", "svg"] }
iced_layershell = "0.13.0"
iced_futures = "0.13.2"

serde = "1.0.217"
serde_json = "1.0.138"

itertools = "0.14.0"
git-version = "0.3.9"

[package]
name = "n16-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
n16-ipc.workspace = true
n16-daemon.workspace = true
