[workspace.package]
name = "n16-shell"
version = "0.1.1"
edition = "2024"

[workspace]
members = [
  "n16-application",
  "n16-bar",
  "n16-daemon",
  "n16-ipc",
  "n16-launcher",
  "n16-theme",
  "n16-widget",
]

[workspace.dependencies]
n16-theme = { path = "./n16-theme" }
n16-widget = { path = "./n16-widget" }
n16-application = { path = "./n16-application" }
n16-ipc = { path = "./n16-ipc" }
n16-daemon = { path = "./n16-daemon" }

n16-launcher = { path = "./n16-launcher" }
n16-bar = { path = "./n16-bar" }

iced = { version = "0.13.1", features = ["tokio", "advanced", "image", "svg"] }
iced_layershell = "0.13.0"
iced_futures = "0.13.2"

serde = "1.0.217"
serde_json = "1.0.138"

tokio = { version = "1.44.2", features = ["net", "io-util"] }
tokio-stream = { version = "0.1.17", features = ["net"] }

itertools = "0.14.0"
git-version = "0.3.9"
rustix = { version = "1.0.5", features = ["process"]}

[package]
name = "n16-shell"
version.workspace = true
edition.workspace = true

[[bin]]
name = "n16"
path = "src/main.rs"

[dependencies]
n16-ipc.workspace = true
n16-daemon.workspace = true

serde.workspace = true
serde_json.workspace = true

clap = { version = "4.5.30", features = ["derive"] }
