[workspace.package]
name = "n16-shell"
version = "0.1.1"
edition = "2024"

[workspace]
members = [
  "core/*",
  "apps/*",
  "n16-daemon",
  "n16-cli"
]

resolver = "3"

[workspace.dependencies]
n16-theme = { path = "./core/theme" }
n16-widget = { path = "./core/widget" }
n16-application = { path = "./core/application" }
n16-ipc = { path = "./core/ipc" }

n16-launcher = { path = "./apps/launcher" }
n16-bar = { path = "./apps/bar" }

iced = { version = "0.13.1", features = ["tokio", "advanced", "image", "svg"] }
iced_layershell = "0.13.0"
iced_futures = "0.13.2"

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

tokio = { version = "1.44.2", features = ["net", "io-util"] }
tokio-stream = { version = "0.1.17", features = ["net"] }

itertools = "0.14.0"
git-version = "0.3.9"
rustix = { version = "1.0.5", features = ["process"]}
