[package]
name = "n16-bar"
version = "0.1.0"
edition = "2021"

[dependencies]
n16-theme.workspace = true
n16-widget.workspace = true
n16-application.workspace = true
n16-ipc.workspace = true

iced.workspace = true
iced_layershell.workspace = true
chrono = "0.4.39"
