[package]
name = "n16-application"
version = "0.1.0"
edition = "2021"

[dependencies]
n16-theme.workspace = true
n16-ipc.workspace = true

iced.workspace = true
iced_layershell.workspace = true
iced_futures.workspace = true
